language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - BLIS_ARCH=reference python setup.py build_ext --inplace
  - BLIS_ARCH=reference pip install -e .
  - pip install pytest-cov
  - pip install coveralls

script:
  - python -m pytest blis --cov=blis

after_success:
  coveralls

notifications:
  email: false
  slack:
    secure: VSqtxg7u4NTZRfoZqjxPRPVS92KTy/mp62egfDZ9ujTP4VPxNe15QZuTB6r/ICPgEYqBtdhLc/aetuBcemt0bHfentV0F7bz7iDY/AFQC1h1i4G0D0wKMufuqOJFw9MOp2tSpuvCVzhCxR+Ymx/F9SaeYBAiwBawce4wu+qu3lA=
